export default {
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: 'white',
  },
  footer: {
    borderWidth: 0.7,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderColor: '#009688',
    borderRadius: 20,
    backgroundColor: '#009688',
    elevation: 2,
    flexDirection: 'row',
  },
  content: {
    flex: 1,
    marginTop: 20,
  },
  addAddress: {
    borderWidth: 0.7,
    paddingVertical: 10,
    paddingHorizontal: 25,
    width: 120,
    borderRadius: 7,
    backgroundColor: '#8D92A3',
    borderColor: '#8D92A3',
  },
  textAdd: {
    fontSize: 10,
    fontFamily: 'Poppins-Light',
    color: 'white',
  },
  footerCheckout: {
    borderWidth: 0.7,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderColor: '#289672',
    borderRadius: 20,
    backgroundColor: '#289672',
    elevation: 2,
    flexDirection: 'row',
  },
  text: {
    fontSize: 17,
    fontFamily: 'ComicNeue-Bold',
    color: 'white',
    flex: 1,
    textAlign: 'center',
  },
  addressWrapper: {
    backgroundColor: '#DEDEDE',
    marginBottom: 10,
    padding: 20,
    borderRadius: 3,
  },
  removeAddress: {
    fontFamily: 'Poppins-Regular',
    textAlign: 'right',
    marginTop: 20,
    color: '#FF8080',
  },
  errorText: {
    fontFamily: 'Poppins-Regular',
    color: '#FF8080',
    fontSize: 12,
    marginLeft: 5,
    marginTop: 5,
  },
};
